/*
peek-into-github

Developed by Rishabh Rao
rishabhsrao.wordpress.com
rishabhsrao@gmail.com
twitter.com/rishabhsrao

This file is a part of peek-into-github.

peek-into-github is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

peek-into-github is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with peek-into-github. If not, see <http://www.gnu.org/licenses/>.
*/
package risbee.pig.core.ui;

import org.openide.util.NbPreferences;

final class PigPanel extends javax.swing.JPanel {

	private final PigOptionsPanelController controller;

	PigPanel(PigOptionsPanelController controller) {
		this.controller = controller;
		initComponents();
		// TODO listen to changes in form fields and call controller.changed()
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pigOptionsContainerPanel = new javax.swing.JPanel();
        githubUsernameLabel = new javax.swing.JLabel();
        githubUsernameTextField = new javax.swing.JTextField();

        pigOptionsContainerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(PigPanel.class, "PigPanel.pigOptionsContainerPanel.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(githubUsernameLabel, org.openide.util.NbBundle.getMessage(PigPanel.class, "PigPanel.githubUsernameLabel.text")); // NOI18N

        githubUsernameTextField.setText(org.openide.util.NbBundle.getMessage(PigPanel.class, "PigPanel.githubUsernameTextField.text")); // NOI18N
        githubUsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                githubUsernameTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pigOptionsContainerPanelLayout = new javax.swing.GroupLayout(pigOptionsContainerPanel);
        pigOptionsContainerPanel.setLayout(pigOptionsContainerPanelLayout);
        pigOptionsContainerPanelLayout.setHorizontalGroup(
            pigOptionsContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pigOptionsContainerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(githubUsernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(githubUsernameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addContainerGap())
        );
        pigOptionsContainerPanelLayout.setVerticalGroup(
            pigOptionsContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pigOptionsContainerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pigOptionsContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(githubUsernameLabel)
                    .addComponent(githubUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(291, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pigOptionsContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pigOptionsContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

	private void githubUsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_githubUsernameTextFieldActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_githubUsernameTextFieldActionPerformed

	void load() {
		// TODO read settings and initialize GUI
		// Example:        
		// someCheckBox.setSelected(Preferences.userNodeForPackage(PigPanel.class).getBoolean("someFlag", false));
		// or for org.openide.util with API spec. version >= 7.4:
		// someCheckBox.setSelected(NbPreferences.forModule(PigPanel.class).getBoolean("someFlag", false));
		// or:
		// someTextField.setText(SomeSystemOption.getDefault().getSomeStringProperty());
		
		// Retrieve the Github username.
		githubUsernameTextField.setText(NbPreferences.forModule(PigPanel.class).get("githubUsername", ""));
	}

	void store() {
		// TODO store modified settings
		// Example:
		// Preferences.userNodeForPackage(PigPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
		// or for org.openide.util with API spec. version >= 7.4:
		// NbPreferences.forModule(PigPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
		// or:
		// SomeSystemOption.getDefault().setSomeStringProperty(someTextField.getText());
		
		// Store the Github username.
		NbPreferences.forModule(PigPanel.class).put("githubUsername", githubUsernameTextField.getText());
	}

	boolean valid() {
		// check whether form is consistent and complete
		
		// Don't allow an empty username.
		if(githubUsernameTextField.getText().trim().isEmpty()) {
			return false;
		} else {
			return true;
		}
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel githubUsernameLabel;
    private javax.swing.JTextField githubUsernameTextField;
    private javax.swing.JPanel pigOptionsContainerPanel;
    // End of variables declaration//GEN-END:variables
}
