/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package risbee.pig.core.ui;

import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//risbee.pig.core.ui//Pig//EN",
autostore = false)
@TopComponent.Description(preferredID = "PigTopComponent",
iconBase = "risbee/pig/core/res/animals-bumble_bee.png",
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "rightSlidingSide", openAtStartup = false)
@ActionID(category = "Window", id = "risbee.pig.core.ui.PigTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_PigAction",
preferredID = "PigTopComponent")
public final class PigTopComponent extends TopComponent {

	public PigTopComponent() {
		initComponents();
		setName(NbBundle.getMessage(PigTopComponent.class, "CTL_PigTopComponent"));
		setToolTipText(NbBundle.getMessage(PigTopComponent.class, "HINT_PigTopComponent"));

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pigContainerPanel = new javax.swing.JPanel();
        treeTableSplitPane = new javax.swing.JSplitPane();
        treeScrollPane = new javax.swing.JScrollPane();
        pigTree = new javax.swing.JTree();
        tableScrollPane = new javax.swing.JScrollPane();
        pigTable = new javax.swing.JTable();

        pigContainerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(PigTopComponent.class, "PigTopComponent.pigContainerPanel.border.title"))); // NOI18N
        pigContainerPanel.setLayout(new javax.swing.BoxLayout(pigContainerPanel, javax.swing.BoxLayout.Y_AXIS));

        treeTableSplitPane.setDividerLocation(125);
        treeTableSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("User");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Repositories");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("ProjectOne");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("ProjectTwo");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        pigTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        treeScrollPane.setViewportView(pigTree);

        treeTableSplitPane.setTopComponent(treeScrollPane);

        pigTable.setAutoCreateRowSorter(true);
        pigTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Property", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pigTable.setColumnSelectionAllowed(true);
        tableScrollPane.setViewportView(pigTable);
        pigTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        pigTable.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(PigTopComponent.class, "PigTopComponent.pigTable.columnModel.title0_1")); // NOI18N
        pigTable.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(PigTopComponent.class, "PigTopComponent.pigTable.columnModel.title1_1")); // NOI18N

        treeTableSplitPane.setRightComponent(tableScrollPane);

        pigContainerPanel.add(treeTableSplitPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pigContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pigContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pigContainerPanel;
    private javax.swing.JTable pigTable;
    private javax.swing.JTree pigTree;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JScrollPane treeScrollPane;
    private javax.swing.JSplitPane treeTableSplitPane;
    // End of variables declaration//GEN-END:variables
	@Override
	public void componentOpened() {
		// TODO add custom code on component opening
	}

	@Override
	public void componentClosed() {
		// TODO add custom code on component closing
	}

	void writeProperties(java.util.Properties p) {
		// better to version settings since initial version as advocated at
		// http://wiki.apidesign.org/wiki/PropertyFiles
		p.setProperty("version", "1.0");
		// TODO store your settings
	}

	void readProperties(java.util.Properties p) {
		String version = p.getProperty("version");
		// TODO read your settings according to their version
	}
}
